// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1zQhG5UW305Xc9teFN1o37Jqv8vGw-20',
    appId: '1:736872799385:web:3fe1802b80762170e5ac08',
    messagingSenderId: '736872799385',
    projectId: 'todago-53cbf',
    authDomain: 'todago-53cbf.firebaseapp.com',
    storageBucket: 'todago-53cbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNcVMYH2AxZlVjX8W5m6mHS8vBKWEjkI',
    appId: '1:736872799385:android:3567697b68ff2087e5ac08',
    messagingSenderId: '736872799385',
    projectId: 'todago-53cbf',
    storageBucket: 'todago-53cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuoA9ff9ceFPYj-6geJnHS1qbkhFj07LY',
    appId: '1:736872799385:ios:5c51a2490cb1ed55e5ac08',
    messagingSenderId: '736872799385',
    projectId: 'todago-53cbf',
    storageBucket: 'todago-53cbf.firebasestorage.app',
    iosBundleId: 'com.example.todaGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuoA9ff9ceFPYj-6geJnHS1qbkhFj07LY',
    appId: '1:736872799385:ios:5c51a2490cb1ed55e5ac08',
    messagingSenderId: '736872799385',
    projectId: 'todago-53cbf',
    storageBucket: 'todago-53cbf.firebasestorage.app',
    iosBundleId: 'com.example.todaGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1zQhG5UW305Xc9teFN1o37Jqv8vGw-20',
    appId: '1:736872799385:web:6dc395146648cf25e5ac08',
    messagingSenderId: '736872799385',
    projectId: 'todago-53cbf',
    authDomain: 'todago-53cbf.firebaseapp.com',
    storageBucket: 'todago-53cbf.firebasestorage.app',
  );
}
